Basic Main and Menu
coyjiv/java-console-booking pull request #4
Opened 2023-08-03 19:17 UTC by Vladimirov2077

Только основа, красоту наведу позже.

2023-08-03 21:47 UTC, akiselevych requested changes

2023-08-03 21:47 UTC, akiselevych commented on src/controllers/MainController.java
> +}
static методы не надо тут использовать, все методы должен вызывать экземпляр класса.

2023-08-03 21:47 UTC, akiselevych commented on src/Main.java
> +        MainController.run();
метод run надо вызывать у обьекта, экземпляра класса MainController

2023-08-03 21:47 UTC, akiselevych commented on src/controllers/MainController.java
> +        MainController main = new MainController(flightsController, bookingsController);
Все эти сущности желательно создать в main

2023-08-03 21:47 UTC, akiselevych commented on src/controllers/MainController.java
> +        String bookingId = scanner.nextLine();
ID у нас int

2023-08-03 21:47 UTC, akiselevych commented on src/controllers/MainController.java
> +}
То есть, надо все методы переписать на не статические.

2023-08-03 22:47 UTC, akiselevych requested changes

2023-08-03 22:47 UTC, akiselevych commented on src/controllers/MainController.java
>              int choice = scanner.nextInt();
Обьявить переменную int choice лучше вне цикла, а инициализировать уже в цикле, потому что, при каждой итерации создается новая переменная в памяти.

2023-08-03 22:47 UTC, akiselevych commented on src/services/Flights/FlightsService.java
> +    private FlightsDao flightsDao = new FlightsDao();
Так делать нельзя. Сервис должен принимать параметром дао

2023-08-03 22:47 UTC, akiselevych commented on src/services/Flights/FlightsService.java
> +    private FlightsDao flightsDao = new FlightsDao();
ты можешь просто обьявить private FlightsDao flightsDao а в конструкторе присвоить

2023-08-04 07:11 UTC, akiselevych requested changes

2023-08-04 07:11 UTC, akiselevych commented on src/controllers/MainController.java
> +        if (!isIntEntered(scanner)) {
Функция isIntEntered по сути не нужна и ее использование не совсем корректное во всех методах, лучше верни везде как было изначально через hasNextInt

2023-08-04 07:11 UTC, akiselevych commented on src/controllers/MainController.java
> +        if (!isIntEntered(scanner)) {
Остальное все вроде как окей

2023-08-04 10:24 UTC, akiselevych approved these changes

2023-08-04 10:25 UTC, coyjiv approved these changes

2023-08-04 10:25 UTC, coyjiv commented on src/controllers/MainController.java
> +                "_______________________________________\n";
Попробуй использовать синтаксис """ текст """, так выйдет чище, и не нужно будет писать /n и делать конкатенации

2023-08-04 10:25 UTC, merged